//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computers
    {
        public int Id { get; set; }
        public string IP { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string State { get; set; }
    }
}
